let LOAD_USERS = "LOAD_USERS";
let LOAD_USER = "LOAD_USER";
let ADD_USER = "ADD_USER";
let UPDATE_USER = "UPDATE_USER";
let DELETE_USER = "DELETE_USER";

export {LOAD_USER, LOAD_USERS, ADD_USER, UPDATE_USER, DELETE_USER}